In [8]:
type(False)
type(True)

bool

In [11]:
my_str = 'Karamjit'
print(my_str.startswith('K'))
print(my_str.endswith('t'))

True
True


In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list.extend([6, 7, 8])
#does the same as flatten function in numpy. It takes a list of lists and flattens it into a single list.
print(my_list[1:5])

[2, 3, 4, 5]


In [37]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[:2])
type(arr)
arr.shape
#shape tells us the dimensions of the array. In this case, it is a 1D array with 5 elements, so the shape is (5,).
#in case of a 2D array, the shape would be (number of rows, number of columns). For example, if we have a 2D array with 3 rows and 4 columns, the shape would be (3, 4).

arr = np.append(arr, [6, 7, 8])
print(arr)


[1 2]
[1 2 3 4 5 6 7 8]


In [39]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr[1:3 , 0:2]
arr[1:2 , 1:3]
#indexing in numpy is similar to indexing in python lists, 
# but it can be done in multiple dimensions. In the above example, 
# arr[1:3 , 0:2] selects the subarray that includes rows 1 and 2 
# (the second and third rows) and columns 0 and 1 (the first and second columns). 
# This results in the subarray [[4, 5], [7, 8]]. Similarly, arr[1:2 , 1:3] 
# selects the subarray that includes row 1 (the second row) and columns 1 and 2 
# (the second and third columns), resulting in the subarray [[5, 6]].

array([[5, 6]])

In [44]:
arr = np.arange(1,11)
arr
#arange is a function in numpy that creates an array of evenly spaced 
# values within a given range. we can specify the start, stop, and step 
# values to generate the desired array.

arr = np.arange(1, 11, 2)
print(arr)
#In this example, np.arange(1, 11, 2) generates an array starting from 1, 
# up to (but not including) 11, with a step of 2.

[1 3 5 7 9]


In [47]:
print(np.linspace(0, 1, 5))
#linspace is a function in numpy that generates an array of evenly spaced

[0.   0.25 0.5  0.75 1.  ]


In [48]:
arr = np.array([1,2,3,4,5])
arr1 = arr
arr1[2:] = 100
print(arr)
print(arr1)
#In this example, arr1 is a reference to the same array as arr. When we modify 
# arr1, it also modifies arr because they both point to the same underlying 
# data. This is why both arr and arr1 show the same modified values after 
# the change.

[  1   2 100 100 100]
[  1   2 100 100 100]


In [50]:
# To create a copy of the array instead of a reference, 
# we can use the copy() method:

arr2 = arr.copy()
arr2[2:] = 500
print(arr)
print(arr2)

[  1   2 100 100 100]
[  1   2 500 500 500]


In [ ]:
arr<50
#This will return a boolean array where each element is True if the 
# corresponding element in arr is less than 50, and False otherwise. 
# In this case, since all elements in arr are less than 50, 
# the output will be an array of True values.

arr[arr<500]
#This will return a new array containing only the elements of arr that are 
# less than 500.

array([  1,   2, 100, 100, 100])

In [ ]:
np.ones(5)
#The np.ones() function in NumPy is used to create an array filled with ones.
# The argument passed to np.ones() specifies the shape of the array.

np.ones(5,dtype=int)
#By default, np.ones() creates an array of floating-point numbers.
# However, you can specify the data type using the dtype parameter.

array([1, 1, 1, 1, 1])

In [2]:
import numpy as np
np.random.rand(3, 4)
#The np.random.rand() function in NumPy is used to generate an array of random 
# numbers between 0 and 1. The arguments passed to np.random.rand() specify 
# the shape


np.random.randint(1, 10, size=(3, 4))
#The np.random.randint() function in NumPy is used to generate an array of random


np.random.random_sample((3, 4))
#The np.random.random_sample() function in NumPy is used to generate an array of random

array([[0.47170483, 0.1655985 , 0.2936345 , 0.17056618],
       [0.62993131, 0.61001748, 0.12636693, 0.19922091],
       [0.16554348, 0.0877205 , 0.0020436 , 0.81945775]])